import React from "react";

export default [
  {
    id: 1,
    firstName: "Kahaleel",
    lastName: "Nitti",
    bandname: "Automated",
    bio: "Front-line multi-state contingency",
    recommendations: "Voolia",
  },
  {
    id: 2,
    firstName: "Sean",
    lastName: "Halpeine",
    bandname: "contingency",
    bio: "Sharable intangible structure",
    recommendations: "Divavu",
  },
  {
    id: 3,
    firstName: "Adriano",
    lastName: "Ferier",
    bandname: "Implemented",
    bio: "Synergistic multi-state function",
    recommendations: "Voolia",
  },
  {
    id: 4,
    firstName: "Rennie",
    lastName: "Hrinchenko",
    bandname: "frame",
    bio: "Open-architected eco-centric attitude",
    recommendations: "Photojam",
  },
  {
    id: 5,
    firstName: "Jeannette",
    lastName: "Tuffley",
    bandname: "Business-focused",
    bio: "Reactive methodical alliance",
    recommendations: "Quimm",
  },
  {
    id: 6,
    firstName: "Aprilette",
    lastName: "Cockhill",
    bandname: "Universal",
    bio: "Exclusive motivating hub",
    recommendations: "Twimbo",
  },
  {
    id: 7,
    firstName: "Bird",
    lastName: "Artharg",
    bandname: "intranet",
    bio: "Reactive heuristic help-desk",
    recommendations: "Kwideo",
  },
  {
    id: 8,
    firstName: "Judye",
    lastName: "Marchenko",
    bandname: "website",
    bio: "Fundamental eco-centric workforce",
    recommendations: "Thoughtstorm",
  },
  {
    id: 9,
    firstName: "Murielle",
    lastName: "Gowers",
    bandname: "mobile",
    bio: "Triple-buffered bifurcated throughput",
    recommendations: "Jaxnation",
  },
  {
    id: 10,
    firstName: "Panchito",
    lastName: "Cello",
    bandname: "projection",
    bio: "Operative responsive neural-net",
    recommendations: "Browsezoom",
  },
  {
    id: 11,
    firstName: "Hailey",
    lastName: "Windross",
    bandname: "infrastructure",
    bio: "Cross-platform bifurcated knowledge user",
    recommendations: "Cogilith",
  },
  {
    id: 12,
    firstName: "Dennison",
    lastName: "Billborough",
    bandname: "Managed",
    bio: "Diverse fresh-thinking definition",
    recommendations: "Brainbox",
  },
  {
    id: 13,
    firstName: "Rowena",
    lastName: "Seagrave",
    bandname: "Future-proofed",
    bio: "Object-based foreground local area network",
    recommendations: "Aivee",
  },
  {
    id: 14,
    firstName: "Danni",
    lastName: "Stuchburie",
    bandname: "throughput",
    bio: "Realigned zero administration open system",
    recommendations: "Aivee",
  },
  {
    id: 15,
    firstName: "Regina",
    lastName: "Beardmore",
    bandname: "Up-sized",
    bio: "Secured multimedia frame",
    recommendations: "Trunyx",
  },
  {
    id: 16,
    firstName: "Rosemary",
    lastName: "Kovacs",
    bandname: "middleware",
    bio: "Automated full-range leverage",
    recommendations: "Photobug",
  },
  {
    id: 17,
    firstName: "Jude",
    lastName: "Charlet",
    bandname: "cohesive",
    bio: "Proactive static monitoring",
    recommendations: "Jaxworks",
  },
  {
    id: 18,
    firstName: "Andreas",
    lastName: "Cockton",
    bandname: "productivity",
    bio: "Fundamental client-driven benchmark",
    recommendations: "Linkbridge",
  },
  {
    id: 19,
    firstName: "Corrie",
    lastName: "Pavlov",
    bandname: "Visionary",
    bio: "Face to face grid-enabled project",
    recommendations: "Meemm",
  },
  {
    id: 20,
    firstName: "Rosalinde",
    lastName: "Buck",
    bandname: "archive",
    bio: "Face to face coherent intranet",
    recommendations: "Voomm",
  },
  {
    id: 21,
    firstName: "Raquela",
    lastName: "Lambal",
    bandname: "Graphic Interface",
    bio: "Mandatory multimedia installation",
    recommendations: "Skalith",
  },
  {
    id: 22,
    firstName: "Kayne",
    lastName: "Henden",
    bandname: "human-resource",
    bio: "Vision-oriented multimedia benchmark",
    recommendations: "Digitube",
  },
  {
    id: 23,
    firstName: "Shermie",
    lastName: "Westall",
    bandname: "multi-state",
    bio: "Distributed impactful approach",
    recommendations: "Fivechat",
  },
  {
    id: 24,
    firstName: "Zaneta",
    lastName: "Haseley",
    bandname: "alliance",
    bio: "Triple-buffered bi-directional process improvement",
    recommendations: "Feedfish",
  },
  {
    id: 25,
    firstName: "Petronia",
    lastName: "Rosingdall",
    bandname: "Automated",
    bio: "Integrated non-volatile adapter",
    recommendations: "Edgeblab",
  },
  {
    id: 26,
    firstName: "Libbi",
    lastName: "Fawbert",
    bandname: "Cross-platform",
    bio: "Adaptive neutral middleware",
    recommendations: "Quimm",
  },
  {
    id: 27,
    firstName: "Abbe",
    lastName: "Danhel",
    bandname: "superstructure",
    bio: "Customer-focused coherent infrastructure",
    recommendations: "Dablist",
  },
  {
    id: 28,
    firstName: "Abigail",
    lastName: "Hallworth",
    bandname: "infrastructure",
    bio: "Customer-focused optimal database",
    recommendations: "Quamba",
  },
  {
    id: 29,
    firstName: "Anthony",
    lastName: "Penswick",
    bandname: "Digitized",
    bio: "Focused contextually-based framework",
    recommendations: "Realbridge",
  },
  {
    id: 30,
    firstName: "Stavros",
    lastName: "Coom",
    bandname: "archive",
    bio: "De-engineered fault-tolerant array",
    recommendations: "Voonte",
  },
  {
    id: 31,
    firstName: "Doti",
    lastName: "Gillson",
    bandname: "Persistent",
    bio: "Extended real-time local area network",
    recommendations: "Yamia",
  },
  {
    id: 32,
    firstName: "Faunie",
    lastName: "Foxcroft",
    bandname: "dynamic",
    bio: "Reduced non-volatile throughput",
    recommendations: "Leenti",
  },
  {
    id: 33,
    firstName: "Grantley",
    lastName: "Demkowicz",
    bandname: "Right-sized",
    bio: "Grass-roots object-oriented internet solution",
    recommendations: "Devpoint",
  },
  {
    id: 34,
    firstName: "Betty",
    lastName: "Penwarden",
    bandname: "holistic",
    bio: "Optional hybrid matrix",
    recommendations: "Meejo",
  },
  {
    id: 35,
    firstName: "Leighton",
    lastName: "Goodley",
    bandname: "Horizontal",
    bio: "Ameliorated multimedia hierarchy",
    recommendations: "Voonder",
  },
  {
    id: 36,
    firstName: "Berkly",
    lastName: "Gain",
    bandname: "Configurable",
    bio: "Open-architected bi-directional attitude",
    recommendations: "Yombu",
  },
  {
    id: 37,
    firstName: "Myriam",
    lastName: "Toolin",
    bandname: "Robust",
    bio: "Extended bandwidth-monitored project",
    recommendations: "Yoveo",
  },
  {
    id: 38,
    firstName: "Nevsa",
    lastName: "Ainley",
    bandname: "impactful",
    bio: "De-engineered zero defect groupware",
    recommendations: "Skipstorm",
  },
  {
    id: 39,
    firstName: "Niles",
    lastName: "Vicent",
    bandname: "zero tolerance",
    bio: "Customer-focused leading edge collaboration",
    recommendations: "Jabberstorm",
  },
  {
    id: 40,
    firstName: "Kathleen",
    lastName: "Chateau",
    bandname: "software",
    bio: "Re-contextualized object-oriented standardization",
    recommendations: "Oyoba",
  },
  {
    id: 41,
    firstName: "Kanya",
    lastName: "Lackney",
    bandname: "optimal",
    bio: "Vision-oriented systematic infrastructure",
    recommendations: "Dynazzy",
  },
  {
    id: 42,
    firstName: "Sadye",
    lastName: "De Lorenzo",
    bandname: "structure",
    bio: "Streamlined intermediate Graphic Interface",
    recommendations: "Kwimbee",
  },
  {
    id: 43,
    firstName: "Fin",
    lastName: "Spence",
    bandname: "database",
    bio: "Intuitive radical infrastructure",
    recommendations: "Trilith",
  },
  {
    id: 44,
    firstName: "Aldric",
    lastName: "Rosenthal",
    bandname: "modular",
    bio: "Realigned transitional customer loyalty",
    recommendations: "Jetpulse",
  },
  {
    id: 45,
    firstName: "Babara",
    lastName: "Delph",
    bandname: "throughput",
    bio: "Profit-focused fault-tolerant moderator",
    recommendations: "Camimbo",
  },
  {
    id: 46,
    firstName: "Ruddie",
    lastName: "Singleton",
    bandname: "software",
    bio: "Decentralized incremental forecast",
    recommendations: "Fanoodle",
  },
  {
    id: 47,
    firstName: "Langsdon",
    lastName: "Feldmesser",
    bandname: "6th generation",
    bio: "Devolved encompassing matrix",
    recommendations: "Yata",
  },
  {
    id: 48,
    firstName: "Krystal",
    lastName: "Penswick",
    bandname: "foreground",
    bio: "Face to face upward-trending website",
    recommendations: "Quimm",
  },
  {
    id: 49,
    firstName: "Forrest",
    lastName: "Shalcras",
    bandname: "framework",
    bio: "Exclusive attitude-oriented parallelism",
    recommendations: "Edgepulse",
  },
  {
    id: 50,
    firstName: "Claybourne",
    lastName: "Poskitt",
    bandname: "optimal",
    bio: "Switchable transitional customer loyalty",
    recommendations: "Twiyo",
  },
  {
    id: 51,
    firstName: "Karita",
    lastName: "Pietruschka",
    bandname: "matrices",
    bio: "Virtual secondary parallelism",
    recommendations: "Wordify",
  },
  {
    id: 52,
    firstName: "Debi",
    lastName: "Carnelley",
    bandname: "Networked",
    bio: "Visionary homogeneous moratorium",
    recommendations: "Avavee",
  },
  {
    id: 53,
    firstName: "Pauly",
    lastName: "Norheny",
    bandname: "Customizable",
    bio: "Ergonomic stable project",
    recommendations: "Kanoodle",
  },
  {
    id: 54,
    firstName: "Thia",
    lastName: "L'Amie",
    bandname: "Fundamental",
    bio: "Fully-configurable modular utilisation",
    recommendations: "Skajo",
  },
  {
    id: 55,
    firstName: "Kare",
    lastName: "Briant",
    bandname: "Organized",
    bio: "Universal zero defect methodology",
    recommendations: "Reallinks",
  },
  {
    id: 56,
    firstName: "Kristien",
    lastName: "Boncoeur",
    bandname: "composite",
    bio: "Upgradable web-enabled function",
    recommendations: "Demizz",
  },
  {
    id: 57,
    firstName: "Carolan",
    lastName: "Lackie",
    bandname: "discrete",
    bio: "Synergistic clear-thinking migration",
    recommendations: "Youbridge",
  },
  {
    id: 58,
    firstName: "Dacy",
    lastName: "Gerardot",
    bandname: "framework",
    bio: "Exclusive user-facing forecast",
    recommendations: "Eire",
  },
  {
    id: 59,
    firstName: "Skipp",
    lastName: "Scripps",
    bandname: "User-friendly",
    bio: "Re-contextualized object-oriented migration",
    recommendations: "Topicblab",
  },
  {
    id: 60,
    firstName: "Cornall",
    lastName: "Degoe",
    bandname: "full-range",
    bio: "Profit-focused demand-driven policy",
    recommendations: "Feedfish",
  },
  {
    id: 61,
    firstName: "Mayne",
    lastName: "Iggalden",
    bandname: "client-driven",
    bio: "Persevering motivating success",
    recommendations: "Edgewire",
  },
  {
    id: 62,
    firstName: "Hunfredo",
    lastName: "Whitsey",
    bandname: "Front-line",
    bio: "Future-proofed 4th generation architecture",
    recommendations: "Twitterwire",
  },
  {
    id: 63,
    firstName: "Ediva",
    lastName: "Speed",
    bandname: "Distributed",
    bio: "Multi-lateral web-enabled info-mediaries",
    recommendations: "Trilia",
  },
  {
    id: 64,
    firstName: "Mireille",
    lastName: "Fransoni",
    bandname: "demand-driven",
    bio: "Upgradable bifurcated encoding",
    recommendations: "Ailane",
  },
  {
    id: 65,
    firstName: "Maryanne",
    lastName: "Jeram",
    bandname: "benchmark",
    bio: "Team-oriented secondary archive",
    recommendations: "Eadel",
  },
  {
    id: 66,
    firstName: "Phillipe",
    lastName: "Commander",
    bandname: "workforce",
    bio: "Innovative contextually-based circuit",
    recommendations: "Roomm",
  },
  {
    id: 67,
    firstName: "Augustine",
    lastName: "Cusiter",
    bandname: "empowering",
    bio: "Customer-focused actuating internet solution",
    recommendations: "Skinder",
  },
  {
    id: 68,
    firstName: "Percival",
    lastName: "Tirkin",
    bandname: "Reverse-engineered",
    bio: "Total zero defect instruction set",
    recommendations: "Tagopia",
  },
  {
    id: 69,
    firstName: "Tallulah",
    lastName: "Scud",
    bandname: "Seamless",
    bio: "Stand-alone discrete capacity",
    recommendations: "Photofeed",
  },
  {
    id: 70,
    firstName: "Evangelina",
    lastName: "Ivey",
    bandname: "3rd generation",
    bio: "Front-line actuating database",
    recommendations: "Flipstorm",
  },
  {
    id: 71,
    firstName: "Stormy",
    lastName: "Spinella",
    bandname: "Multi-lateral",
    bio: "Vision-oriented discrete infrastructure",
    recommendations: "Voonte",
  },
  {
    id: 72,
    firstName: "Lisle",
    lastName: "MacVean",
    bandname: "coherent",
    bio: "Phased system-worthy adapter",
    recommendations: "Yambee",
  },
  {
    id: 73,
    firstName: "Grange",
    lastName: "Kingsbury",
    bandname: "task-force",
    bio: "Customer-focused bottom-line adapter",
    recommendations: "Eidel",
  },
  {
    id: 74,
    firstName: "Drucill",
    lastName: "Jennaway",
    bandname: "hub",
    bio: "Right-sized 24 hour conglomeration",
    recommendations: "Dabvine",
  },
  {
    id: 75,
    firstName: "Baird",
    lastName: "Dumbreck",
    bandname: "Robust",
    bio: "Stand-alone systematic orchestration",
    recommendations: "Vinder",
  },
  {
    id: 76,
    firstName: "Carey",
    lastName: "Beernaert",
    bandname: "zero defect",
    bio: "Sharable static info-mediaries",
    recommendations: "Livefish",
  },
  {
    id: 77,
    firstName: "Dex",
    lastName: "Stebles",
    bandname: "benchmark",
    bio: "Vision-oriented web-enabled capability",
    recommendations: "Youbridge",
  },
  {
    id: 78,
    firstName: "Cthrine",
    lastName: "Biskupek",
    bandname: "Persevering",
    bio: "Front-line actuating budgetary management",
    recommendations: "Jaxworks",
  },
  {
    id: 79,
    firstName: "Theresita",
    lastName: "Staniforth",
    bandname: "Adaptive",
    bio: "Versatile zero tolerance matrices",
    recommendations: "Devpulse",
  },
  {
    id: 80,
    firstName: "Meagan",
    lastName: "Terzo",
    bandname: "Virtual",
    bio: "Team-oriented zero tolerance encoding",
    recommendations: "Gabspot",
  },
  {
    id: 81,
    firstName: "Mycah",
    lastName: "Tweddell",
    bandname: "complexity",
    bio: "Ameliorated eco-centric circuit",
    recommendations: "Wikizz",
  },
  {
    id: 82,
    firstName: "Welby",
    lastName: "Ridsdale",
    bandname: "Persistent",
    bio: "Realigned national extranet",
    recommendations: "Dabjam",
  },
  {
    id: 83,
    firstName: "Godard",
    lastName: "Celloni",
    bandname: "success",
    bio: "Mandatory bi-directional methodology",
    recommendations: "Edgewire",
  },
  {
    id: 84,
    firstName: "Margie",
    lastName: "Babbage",
    bandname: "core",
    bio: "Horizontal user-facing policy",
    recommendations: "Katz",
  },
  {
    id: 85,
    firstName: "Codi",
    lastName: "Dodgson",
    bandname: "bandwidth-monitored",
    bio: "Open-source grid-enabled conglomeration",
    recommendations: "Dynabox",
  },
  {
    id: 86,
    firstName: "Leupold",
    lastName: "Hicks",
    bandname: "Expanded",
    bio: "Implemented multimedia installation",
    recommendations: "Skivee",
  },
  {
    id: 87,
    firstName: "Minna",
    lastName: "Exrol",
    bandname: "3rd generation",
    bio: "Decentralized stable access",
    recommendations: "Zoomcast",
  },
  {
    id: 88,
    firstName: "Carlen",
    lastName: "MacAindreis",
    bandname: "Synergistic",
    bio: "Integrated asymmetric definition",
    recommendations: "Meetz",
  },
  {
    id: 89,
    firstName: "Luca",
    lastName: "Posnett",
    bandname: "info-mediaries",
    bio: "Grass-roots radical task-force",
    recommendations: "Oyoloo",
  },
  {
    id: 90,
    firstName: "Sutton",
    lastName: "Druitt",
    bandname: "fault-tolerant",
    bio: "Advanced intermediate encryption",
    recommendations: "Babbleset",
  },
  {
    id: 91,
    firstName: "Melitta",
    lastName: "Burrell",
    bandname: "directional",
    bio: "Customizable intermediate circuit",
    recommendations: "Jaxnation",
  },
  {
    id: 92,
    firstName: "Corella",
    lastName: "Garmston",
    bandname: "mobile",
    bio: "Re-contextualized human-resource process improvement",
    recommendations: "Camimbo",
  },
  {
    id: 93,
    firstName: "Vere",
    lastName: "Silley",
    bandname: "matrix",
    bio: "Quality-focused attitude-oriented core",
    recommendations: "Voomm",
  },
  {
    id: 94,
    firstName: "Loni",
    lastName: "Burchnall",
    bandname: "help-desk",
    bio: "Multi-layered bottom-line strategy",
    recommendations: "Roodel",
  },
  {
    id: 95,
    firstName: "Rodolph",
    lastName: "Gorling",
    bandname: "exuding",
    bio: "Expanded holistic function",
    recommendations: "Gabtune",
  },
  {
    id: 96,
    firstName: "Ianthe",
    lastName: "Sobey",
    bandname: "monitoring",
    bio: "Fundamental demand-driven encoding",
    recommendations: "Zoonoodle",
  },
  {
    id: 97,
    firstName: "Henka",
    lastName: "Huey",
    bandname: "well-modulated",
    bio: "Fundamental mobile knowledge base",
    recommendations: "Twitterlist",
  },
  {
    id: 98,
    firstName: "Lynn",
    lastName: "Dodridge",
    bandname: "matrices",
    bio: "Implemented bottom-line projection",
    recommendations: "Oyonder",
  },
  {
    id: 99,
    firstName: "Sharleen",
    lastName: "Kettell",
    bandname: "well-modulated",
    bio: "Assimilated logistical analyzer",
    recommendations: "Jayo",
  },
  {
    id: 100,
    firstName: "Loren",
    lastName: "Viccary",
    bandname: "groupware",
    bio: "Open-architected analyzing application",
    recommendations: "Rhyzio",
  },
];
